name: heroku-firstday

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name:  Set up Python 3.9
         uses: actions/setup-python@v2
         with:
            python-version: 3.9
       - name: Install dependencies.
         run: |
              sudo apt update
              sudo apt install ffmpeg
              pip install python-decouple pytz heroku3
              pip install --upgrade pip
       - name: clone
         run: |
              git clone https://${{ secrets.GitHubName }}:${{ secrets.GH_TOKEN }}@${{ secrets.CREDS }} repo
              cd repo || exit 1
              pip3 install -r requirements.txt
              python3 main.py
